# Generated by Django 5.0.6 on 2025-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctscanrecord',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
